name: Bug Report
description: Create a report to help us improve Zix
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - muhammad-fiaz
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: I am experiencing an issue where...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Initialize app with `...`
        2. Run `...`
        3. Send request to `...`
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Zix Version
      description: What version of Zix are you using?
      placeholder: 0.0.1
    validations:
      required: true
  - type: input
    id: zig_version
    attributes:
      label: Zig Version
      description: What version of Zig are you using?
      placeholder: 0.13.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
        - macOS
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please describe any relevant log output.
      render: shell
